### ISSUE TITLE
Tool bleibt bei einer MP3 hängen...

### ISSUE THREAD

**Issue by M4RKU5-C0D3** [raph-ael/tonuino-toolbox#1]
@raph-ael leider läuft es bei mir irgendwie noch nicht richtig :confused: Die Karte hat er wohl eingelesen aber danach passiert nix mehr:

![grafik](https://user-images.githubusercontent.com/3947983/83325005-4ddfcd80-a269-11ea-8305-f9e3305deb8d.png)

tonuino-toolbox-1.1.6-linux-x86_64.AppImage @ Ubuntu 20.04 LTS

**Comment by M4RKU5-C0D3** [comment]
Hier mal der Output:
```
$ ./TonUINO-Toolbox.AppImage
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
(node:23576) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(node:23576) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(node:23576) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(node:23576) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
check for updates
Checking for update
Update for version 1.1.6 is not available (latest version: 1.1.6, downgrade is disallowed).
checkForUpdatesAndNotify called, downloadPromise is null
```

**Comment by M4RKU5-C0D3** [comment]
Ich werde auch noch mal das .deb testen. Die MP3 schicke ich dir mal per PM...

**Comment by raph-ael** [comment]
Jetzt bin ich schon soweit das ich auch unter einem ubuntu 20.04 getestet habe. Aber nichts keine Fehlermeldung.

Ich habe blind an einiges Stellen das Error Handing angepasst und mehr gelogged.

Wenn Du magst gener nochmal mit dieser angepassten AppImage:
https://cloud.geldfrei.net/s/5BPYeZgdDBr5df9

Bei einem bin ich mir sicher die Datei bei der es hängen bleibt muss die Datei sein die nach der mp3 ist die Du mir geschickt hast. Denn Die Status Meldung wird erst angezeigt wenn Die Datei erfolgreich eingelesen wurde.

Es würde also ebenfalls helfen wenn du mir die nachfolgende mp3 nochmal zukommen lässt. Über den Link wie oben https://cloud.geldfrei.net/s/5BPYeZgdDBr5df9 kannst Du auch Dateien hochladen, die landet dann direkt auf meinem Laptop.

**Comment by M4RKU5-C0D3** [comment]
Ich glaube dann habe ich bereits des Rätsels Lösung: Die nächste MP3 wäre die Erste im nächsten Ordner (03) und hatte *kein* ID3-Tag. Nachdem ich den ganzen Ordner mal mit EasyTAG bearbeitet habe läuft's wie geschmiert :smile:

**Comment by raph-ael** [comment]
Alles klar! Danke Dir. Das wird natürlich gepatched.
