### ISSUE TITLE
mp3 and advert folder after cleanup wrong

### ISSUE THREAD

**Issue by HerbyR56** [raph-ael/tonuino-toolbox#5]
I used the Tool. After "SD Karte säubern", the files in the mp3 and advert folder are wrong. Instead of 0001 there is 001, which is no more the right file to find for the DF-Player. In the mp3 and advert folder, 4 digit file names are necessary (up to 1000 files). Correction is necessary.

**Comment by raph-ael** [comment]
this issue should be fixed in [version 1.1.9](https://github.com/raph-ael/tonuino-toolbox/releases/latest)

**Comment by HerbyR56** [comment]
I have retested, it's working fine now, thank you
